POST  http://127.0.0.1:3000/api/users/register
Content-Type: application/json

{
    "email":"mantas@gmail.com",
    "password":"secret123"
}

###

POST  http://127.0.0.1:3000/api/users/login
Content-Type: application/json

{
    "email":"rokas@gmail.com",
    "password":"secret123"
}
###

GET  http://127.0.0.1:3000/api/questions
###

POST http://127.0.0.1:3000/api/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTEwNTE3NiwiZXhwIjoxNjU5MTA4Nzc2fQ.HB9kRqa-87lTZ7il-EzMOTlAlRf0LXGuISxoup2ddXI
Content-Type: application/json

{
"title":"Rokas test auth OK",
"content":"Rokas test auth OK"
}
###

PATCH http://127.0.0.1:3000/api/questions/7
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTAyOTA1MiwiZXhwIjoxNjU5MDMyNjUyfQ.2y-S9HRw8EYJVD49bFFb2yJx60HD_2uC0q5RORmbnTc
Content-Type: application/json

{
"title":"Fourth test Patched auth",
"content":"Test4 Patched auth"
}
###

DELETE  http://127.0.0.1:3000/api/questions/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTE2NDgxNCwiZXhwIjoxNjU5MTY4NDE0fQ.VG0SVCaAZkbGnhJz_6Ov4On3Vz_bLdc8QpRNwqNPzU8
###

GET  http://127.0.0.1:3000/api/questions/1/answers
###

POST  http://127.0.0.1:3000/api/questions/1/answers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTE2NDgxNCwiZXhwIjoxNjU5MTY4NDE0fQ.VG0SVCaAZkbGnhJz_6Ov4On3Vz_bLdc8QpRNwqNPzU8
Content-Type: application/json

{
    "content":"test3"
}
###

PATCH http://127.0.0.1:3000/api/answers/100
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTExNDIyMiwiZXhwIjoxNjU5MTE3ODIyfQ.kDjNV0q1ot-vDxx6304m5GZghp6Mkx1YRSpO4jsDSik
Content-Type: application/json

{
"content":"Answered patch yes again!!!"
}
###

DELETE  http://127.0.0.1:3000/api/answers/id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTE2NDgxNCwiZXhwIjoxNjU5MTY4NDE0fQ.VG0SVCaAZkbGnhJz_6Ov4On3Vz_bLdc8QpRNwqNPzU8
###

DELETE  http://127.0.0.1:3000/api/answers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTE2NDgxNCwiZXhwIjoxNjU5MTY4NDE0fQ.VG0SVCaAZkbGnhJz_6Ov4On3Vz_bLdc8QpRNwqNPzU8
###

GET http://127.0.0.1:3000/api/answers/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1OTE3NDk1OCwiZXhwIjoxNjU5MTc4NTU4fQ.oqIh-zFpTQhcrNAbA4GdcM-gQJRzJvdjJZPIE7nFoJU
###